In [3]:
import numpy as np

**Check the Version of the Numpy**

In [74]:
np.__version__


'1.13.3'

**Create a new array of random 2*2 integers, without initializing entries.**


In [75]:
np.empty([2,2],int)

array([[0, 1],
       [2, 3]])

**Let X = np.array([1,2,3], [4,5,6], np.int32). Create a new array with the same shape and type as X.**

In [71]:
X = np.array([(1,2,3), (4,5,6)],int)

np.empty_like(X)

array([[1, 2, 3],
       [4, 5, 6]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [13]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [72]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [62]:
np.ones([3,2], float)


array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [77]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1])



Create a new array of 3*2 float numbers, filled with zeros.


In [78]:
np.zeros((3,2), float)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

**Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.**

In [20]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)


array([0, 0, 0, 0])

**Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.**

In [79]:
np.full((2, 5), 6, dtype=np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

In [80]:
np.ones([2, 5], dtype=np.uint) * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

**Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.**


In [81]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6])

In [31]:
x = np.arange(4, dtype=np.int64)
print(x)

[0 1 2 3]


**Create an array of [1,2,3]**

In [82]:
np.array([1,2,3])

array([1, 2, 3])

**Let x = [1, 2]. Convert it into an array.**

In [83]:
x = [1,2]
np.asarray(x)

array([1, 2])

**Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.**

In [85]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

**Let x = [1, 2]. Convert it into an array of float.**

In [88]:
#solution1
x = [1, 2]
np.asfarray(x)

array([ 1.,  2.])

In [89]:
#solution2
np.asarray(x, float)

array([ 1.,  2.])

**Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.**

In [92]:
#solution1
x = np.array([30])
np.asscalar(x)


30

In [94]:
#solution2
x = np.array([30])
x[0]

30

**Let x = np.array([1, 2, 3]). Create a array copy of x.**

In [100]:
x = np.array([1, 2, 3])
y = np.copy(x)
print(x)
print(y)

[1 2 3]
[1 2 3]


**Create an array of 2, 4, 6, 8, ..., 100.**

In [101]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Let X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]]). Get the diagonal of X, that is, [0, 5, 10].**

In [103]:
#solution1
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

In [105]:
#solution2
X.diagonal()

array([ 0,  5, 10])

**Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.**


In [106]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])



**Create an array which looks like below. array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])**


In [144]:
np.tri(3, 5,-1)


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

**Create an array which looks like below. array([[ 0, 0, 0], [ 4, 0, 0], [ 7, 8, 0], [10, 11, 12]])**

In [157]:
np.tril(np.arange(1, 13).reshape(4, 3))

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

**Create an array which looks like below. array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0, 12]])**

In [134]:
np.triu(np.arange(1, 13).reshape(4, 3), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])